### ISSUE TITLE
Version 3.8.0 does not create client package anymore

### ISSUE THREAD

**Issue by MaudeVanhengel** [deweyjose/graphqlcodegen#344]
When upgrading from 3.7.3 to 3.8.0 my project does not compile anymore. The issue is that the new version does not seem to create client packages anymore in the target folder. So all my Projectionroots etc are not found so project is not compiling.

[ERROR] ***REDACTED***/***ResponseHandler.java:[50,29] cannot find symbol
[ERROR]   symbol:   class ***ProjectionRoot
[ERROR]   location: **bResponseHandler

[4,46] package **.client does not exist

versions:
        <dgs.codegen.shared.core.version>8.6.0</dgs.codegen.shared.core.version>
        <graphqlcodegen-maven-plugin.version>3.8.0</graphqlcodegen-maven-plugin.version>

I've also tried dgs version 8.5.0 but same result.
The only thing that helps is downgrading again to 3.7.3

**Comment by deweyjose** [comment]
## Triage

**Category:** Bug — plugin option regression (silent no-op). Very likely a `generateClientApiv2` migration issue introduced in plugin **3.8.0**.

### Findings

The missing `.client` package (`*ProjectionRoot`, `*GraphQLQuery`, …) is produced by the client-API generation options. Between the plugin versions you named, the wiring for the older option changed:

- Plugin **3.8.0** bumped `graphql-dgs-codegen-core` 8.3.0 → 8.5.0 (commit `9fa08b9`). Upstream **removed `generateClientApiv2` in 8.4.0** (the v2 client API was consolidated into `generateClientApi`).
- That commit dropped `generateClientApiv2` from the positional `CodeGenConfig` constructor call in `CodeGenConfigBuilder.build()` (`graphqlcodegen-maven-plugin/src/main/java/io/github/deweyjose/graphqlcodegen/CodeGenConfigBuilder.java:334-379`). The `@Parameter` and setter are retained **only for source compatibility** and are now `@Deprecated` no-ops.
- `CodegenExecutor.java:103` still calls `.setGenerateClientApiv2(...)`, but that setter no longer feeds `build()`, so the value is inert.
- Unlike `omitNullInputFields`, which **logs a warning** when set (see `README.md:740-741`), `generateClientApiv2` is silently ignored — nothing tells you the option stopped doing anything.

So if your `<configuration>` used **`<generateClientApiv2>true</generateClientApiv2>`** (rather than `<generateClientApi>true</generateClientApi>`), then on 3.7.3 it drove client generation, and on 3.8.0 it does nothing → no `.client` package → the compile errors you're seeing. This is a known historical usage pattern (cf. #167, where a user drove client generation via `generateClientApiV2`).

**I verified the constructor is otherwise correctly aligned** to upstream 8.5.0 (`generateClientApi` is forwarded at the right position via `CodegenExecutor.java:102`), so `generateClientApi` itself works — this is specifically about the `v2` option becoming inert.

### Immediate workaround

Switch the option name in your plugin `<configuration>`:

```xml
<generateClientApi>true</generateClientApi>
```

Keep your existing `includeQueries` / `includeMutations` / `typeMapping` as-is. That should restore the `.client` package on 3.8.0.

### Missing info requested

To confirm this is the cause (and rule out a second, genuine bug where `generateClientApi=true` fails to emit the client package), please share:

1. Your plugin `<configuration>` block (specifically: are you using `generateClientApiv2` or `generateClientApi`?).
2. Plugin version (3.8.0) and the exact `graphql-dgs-codegen-core` version if you override it — note the plugin pins **8.5.0** internally regardless of the DGS *framework* version (8.5.0/8.6.0) you mentioned.
3. A minimal `.graphqls` schema and the failing config, ideally against the reproducible harness at https://github.com/deweyjose/graphqlcodegen-example.

### Backwards compatibility

**Not blocking on the compatibility gate.** The change that caused this already shipped in 3.8.0 (the underlying breaking removal happened upstream in 8.4.0 and cannot be reversed here). The fix for you is a config rename (non-breaking), and the fix I'd recommend on the plugin side — **emit a warning when `generateClientApiv2` is set, mirroring `omitNullInputFields`** — only adds a log line, so it is also non-breaking. No `breaking-change` label needed.

Leaving this open pending your config; if you confirm you were on `generateClientApiv2`, the actionable plugin follow-up is the warning log so this failure mode stops being silent.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by MaudeVanhengel** [comment]
@deweyjose I was indeed using generateClientApiv2, wasnt aware of that change. Updated my config and it's now working again
