### ISSUE TITLE
Compilation error in generated DocumentFilesGraphQLQuery after upgrading graphqlcodegen-maven-plugin from 2.x to 3.x

### ISSUE THREAD

**Issue by sogillani** [deweyjose/graphqlcodegen#222]
Hi,

I encountered a compilation issue when upgrading the graphqlcodegen-maven-plugin dependency from version 2.0.0 to 3.0.0 or 3.0.2 in a Maven project that uses graphql-dgs-platform-dependencies (version 10.1.2) and graphql-dgs-codegen-client-core (version 5.1.17)

Description:
The generated DocumentFilesGraphQLQuery class fails to compile due to missing symbols:

getVariableDefinitions()

getVariableReferences()

These methods are referenced in the generated code but do not exist in the current version of the GraphQLQuery class provided by the DGS platform dependencies. This results in compilation errors like:

error: cannot find symbol
  getVariableDefinitions().addAll(variableDefinitions);
  getVariableReferences().putAll(variableReferences);

**Comment by sogillani** [comment]
Thank you, it resolved the issue
